# Generated by Django 5.1.6 on 2025-03-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_surname', models.CharField(default='', max_length=63)),
                ('user_name', models.CharField(default='', max_length=63)),
                ('user_name2', models.CharField(default='', max_length=63)),
                ('date_birth', models.DateTimeField(db_index=True, default=None, null=True)),
                ('comment', models.CharField(default='', max_length=511)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
