# Generated by Django 5.1.6 on 2025-03-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersinfo',
            old_name='time_update',
            new_name='time_create',
        ),
    ]
