# Generated by Django 5.1.6 on 2025-03-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_time_update_usersinfo_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
