# Generated by Django 5.1.6 on 2025-03-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_usersinfo_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='date_birth',
            field=models.DateField(db_index=True, default=None, null=True),
        ),
    ]
